data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL:
  local-data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion/

data_validation:
  root_dir: artifacts/data_validation
  status_file: artifacts/data_validation/status.txt
  all_required_files:
    - train
    - test
    - validation

